'use client'

import { AlertCircle, Bell, Check, CheckCircle2, ChevronRight, CircleUserRound, ClipboardCheck, Copy, KeyRound, LockKeyhole, Mail, MessageSquare, Plus, RefreshCw, Save, Search, Send, Settings2, Shield, Sparkles, Trash2, TriangleAlert, X } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { alerts as initialAlerts, approvals as initialApprovals, notifications as initialNotifications } from '@/lib/smartpark-data'
import { AdminShell, Modal, PageHeader, Status } from './shell'

export function AlertsPage() {
  const [alerts, setAlerts] = useState(initialAlerts); const [filter, setFilter] = useState('All'); const [selected, setSelected] = useState(initialAlerts[0]);
  const visible = alerts.filter(a => filter === 'All' || a.severity === filter)
  return <AdminShell><PageHeader title="System alerts" description="Review security events, capacity warnings, and infrastructure notices." action={<button className="button-secondary" onClick={() => setAlerts([])}><Check />Acknowledge all</button>} /><div className="grid gap-4 xl:grid-cols-[1fr_360px]"><section className="panel overflow-hidden"><div className="flex gap-2 overflow-x-auto border-b p-4">{['All','Critical','Warning','Info'].map(x => <button key={x} onClick={() => setFilter(x)} className={`filter-chip ${filter === x ? 'filter-chip-active' : ''}`}>{x}</button>)}</div><div>{visible.length ? visible.map(a => <button key={a.id} onClick={() => setSelected(a)} className={`alert-row w-full text-left ${selected?.id === a.id ? 'bg-muted/70' : ''}`}><span className={`alert-icon alert-${a.severity.toLowerCase()}`}>{a.severity === 'Critical' ? <TriangleAlert /> : a.severity === 'Warning' ? <AlertCircle /> : <Bell />}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-semibold">{a.title}</p><Status tone={a.severity === 'Critical' ? 'danger' : a.severity === 'Warning' ? 'warning' : 'info'}>{a.severity}</Status></div><p className="mt-1 text-sm text-muted-foreground">{a.text}</p><p className="mt-2 text-xs text-muted-foreground">{a.time}</p></div><ChevronRight /></button>) : <Empty title="No active alerts" text="All alerts have been acknowledged." />}</div></section>{selected && <aside className="panel self-start p-5"><p className="section-kicker">Alert details</p><h2 className="mt-3 text-xl font-semibold">{selected.title}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{selected.text}</p><div className="mt-6 rounded-xl bg-muted p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Suggested action</p><p className="mt-2 text-sm">Review entrance camera footage and verify the vehicle against the temporary guest list.</p></div><div className="mt-6 flex flex-col gap-2"><button className="button-primary justify-center" onClick={() => setAlerts(a => a.filter(x => x.id !== selected.id))}><CheckCircle2 />Acknowledge</button><button className="button-secondary justify-center">View source event</button></div></aside>}</div></AdminShell>
}

export function NotificationsPage() {
  const [items, setItems] = useState(initialNotifications); const [filter, setFilter] = useState('All'); const shown = items.filter(n => filter === 'All' || (filter === 'Unread' && n.unread))
  return <AdminShell><PageHeader title="Notifications" description="Stay up to date with parking activity, requests, and system updates." action={<button className="button-secondary" onClick={() => setItems(items.map(n => ({...n, unread:false})))}><Check />Mark all as read</button>} /><section className="panel mx-auto max-w-4xl overflow-hidden"><div className="flex items-center justify-between border-b p-4"><div className="flex gap-2">{['All','Unread'].map(x => <button key={x} onClick={() => setFilter(x)} className={`filter-chip ${filter === x ? 'filter-chip-active' : ''}`}>{x}</button>)}</div><button className="icon-button"><Settings2 /></button></div>{shown.map(n => <button key={n.id} onClick={() => setItems(items.map(x => x.id === n.id ? {...x, unread:false} : x))} className="notification-row w-full text-left"><span className={`table-icon ${n.unread ? 'bg-primary/10 text-primary' : ''}`}><Bell /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-semibold">{n.title}</p>{n.unread && <span className="size-2 rounded-full bg-primary" />}</div><p className="mt-1 text-sm text-muted-foreground">{n.text}</p><p className="mt-2 text-xs text-muted-foreground">{n.time}</p></div><button className="icon-button" onClick={e => { e.stopPropagation(); setItems(items.filter(x => x.id !== n.id)) }}><X /></button></button>)}</section></AdminShell>
}

export function ApprovalsPage() {
  const [items, setItems] = useState(initialApprovals); const [selected, setSelected] = useState(initialApprovals[0]); const [open, setOpen] = useState(false)
  function decide(status: string) { setItems(items.filter(x => x.id !== selected.id)); setOpen(false) }
  return <AdminShell><PageHeader title="Approval center" description="Review resident access, vehicle registrations, and guest parking requests." action={<Status tone="warning">{items.length} pending</Status>} /><section className="grid gap-4 lg:grid-cols-3"><SummaryBox label="Pending review" value={String(items.length)} icon={ClipboardCheck} /><SummaryBox label="Approved today" value="18" icon={CheckCircle2} /><SummaryBox label="Avg. response" value="24m" icon={RefreshCw} /></section><section className="panel mt-4 overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 md:flex-row"><label className="search-field flex-1"><Search /><input placeholder="Search requests" /></label><select><option>All request types</option><option>Resident access</option><option>Vehicle registration</option></select></div><div className="table-wrap"><table><thead><tr><th>Request</th><th>Applicant</th><th>Type</th><th>Submitted</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(a => <tr key={a.id}><td className="font-mono font-semibold">{a.id}</td><td><p className="font-semibold">{a.person}</p><p className="text-xs text-muted-foreground">{a.detail}</p></td><td>{a.kind}</td><td>{a.submitted}</td><td><Status tone="warning">Pending</Status></td><td><button className="text-button" onClick={() => {setSelected(a); setOpen(true)}}>Review</button></td></tr>)}</tbody></table></div>{!items.length && <Empty title="Queue cleared" text="There are no more requests to review." />}</section><Modal open={open} onClose={() => setOpen(false)} title={`Review ${selected.id}`}><div className="flex flex-col gap-4"><div className="rounded-xl bg-muted p-4"><p className="text-lg font-semibold">{selected.person}</p><p className="text-sm text-muted-foreground">{selected.detail}</p></div><Detail label="Request type" value={selected.kind} /><Detail label="Submitted" value={selected.submitted} /><Detail label="Verification" value="Identity and unit verified" /><label className="field"><span>Review note</span><textarea rows={3} placeholder="Optional note for the applicant" /></label><div className="grid grid-cols-2 gap-2"><button className="button-secondary justify-center text-destructive" onClick={() => decide('Rejected')}><X />Reject</button><button className="button-primary justify-center" onClick={() => decide('Approved')}><Check />Approve</button></div></div></Modal></AdminShell>
}

export function AssistantPage() {
  const [messages, setMessages] = useState([{role:'assistant', text:'Good morning, Alex. I can help you understand occupancy, investigate parking events, or recommend operational actions. What would you like to know?'}]); const [input,setInput]=useState('');
  function send(e:FormEvent){e.preventDefault(); if(!input.trim())return; const q=input; setMessages([...messages,{role:'user',text:q},{role:'assistant',text:'Based on current data, occupancy is trending 6% above the weekly baseline. North Tower will likely reach 91% capacity around 6:10 PM. I recommend opening 18 overflow spaces on Level B2.'}]);setInput('')}
  return <AdminShell><div className="mx-auto flex h-[calc(100vh-7.5rem)] max-w-5xl flex-col"><PageHeader eyebrow="SmartPark Copilot" title="AI assistant" description="Ask questions about occupancy, residents, access events, or property performance." action={<button className="button-secondary" onClick={() => setMessages([])}><Plus />New chat</button>} /><section className="panel flex min-h-0 flex-1 flex-col overflow-hidden"><div className="flex-1 overflow-y-auto p-4 md:p-6"><div className="mx-auto flex max-w-3xl flex-col gap-5">{messages.length === 0 && <Empty title="Start a new conversation" text="Ask about your properties, parking demand, or recent events." />}{messages.map((m,i)=><div key={i} className={`flex gap-3 ${m.role==='user'?'justify-end':''}`}>{m.role==='assistant'&&<span className="stat-icon stat-primary shrink-0"><Sparkles /></span>}<div className={`message ${m.role==='user'?'message-user':'message-assistant'}`}><p>{m.text}</p>{m.role==='assistant'&&i>0&&<div className="mt-4 flex gap-2 border-t pt-3"><button className="text-button"><Copy />Copy</button><button className="text-button">View data</button></div>}</div></div>)}</div></div><div className="border-t p-4"><div className="mx-auto mb-3 flex max-w-3xl gap-2 overflow-x-auto">{['Forecast tonight’s peak','Show critical alerts','Which spaces are underused?'].map(q=><button key={q} className="filter-chip whitespace-nowrap" onClick={()=>setInput(q)}>{q}</button>)}</div><form onSubmit={send} className="mx-auto flex max-w-3xl items-end gap-2 rounded-2xl border bg-muted/40 p-2"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&e.keyCode!==229){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} rows={2} placeholder="Ask SmartPark AI…" className="min-h-12 flex-1 resize-none border-0 bg-transparent p-2 outline-none"/><button className="button-primary size-11 justify-center p-0" aria-label="Send message"><Send /></button></form></div></section></div></AdminShell>
}

export function SettingsPage() {
  const [tab,setTab]=useState('General'); const [saved,setSaved]=useState(false); const tabs=['General','Parking rules','Notifications','Security','Integrations']
  return <AdminShell><PageHeader title="Settings" description="Configure your portfolio, policies, notifications, and workspace security." action={<button className="button-primary" onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)}}><Save />{saved?'Saved':'Save changes'}</button>} /><div className="grid gap-4 lg:grid-cols-[240px_1fr]"><nav className="panel self-start p-2">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`settings-tab ${tab===t?'settings-tab-active':''}`}>{t==='General'?<CircleUserRound/>:t==='Parking rules'?<ClipboardCheck/>:t==='Notifications'?<Bell/>:t==='Security'?<Shield/>:<KeyRound/>}{t}</button>)}</nav><section className="panel p-5 md:p-7"><h2 className="text-xl font-semibold">{tab}</h2><p className="mt-1 text-sm text-muted-foreground">Manage your {tab.toLowerCase()} configuration.</p>{tab==='General'?<div className="mt-7 flex max-w-2xl flex-col gap-5"><label className="field"><span>Property name</span><input defaultValue="Northpoint Residences" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="field"><span>Timezone</span><select defaultValue="Pacific Time"><option>Pacific Time</option><option>Mountain Time</option><option>Eastern Time</option></select></label><label className="field"><span>Parking capacity</span><input type="number" defaultValue="2066" /></label></div><label className="field"><span>Support email</span><input type="email" defaultValue="parking@northpoint.com" /></label></div>:<div className="mt-7 flex flex-col gap-2">{settingRows[tab]?.map((x,i)=><div key={x[0]} className="flex items-center justify-between gap-6 rounded-xl border p-4"><div><p className="font-medium">{x[0]}</p><p className="mt-1 text-xs text-muted-foreground">{x[1]}</p></div><label className="switch"><input type="checkbox" defaultChecked={i!==2}/><span /></label></div>)}</div>}{tab==='Security'&&<div className="mt-8 rounded-xl border border-destructive/25 bg-destructive/5 p-4"><p className="font-semibold text-destructive">Danger zone</p><p className="mt-1 text-sm text-muted-foreground">Remove all demo activity and restore workspace defaults.</p><button className="button-secondary mt-4 text-destructive"><Trash2 />Reset workspace</button></div>}</section></div></AdminShell>
}

const settingRows:Record<string,string[][]>={
  'Parking rules':[['Allow guest extensions','Residents can extend active guest passes.'],['Enable automatic assignments','AI assigns the best available space.'],['Permit overnight parking','Allow vehicles to remain after midnight.']],
  'Notifications':[['Critical security alerts','Notify admins immediately.'],['Approval requests','Send alerts for new requests.'],['Weekly performance digest','Receive a Monday morning report.']],
  'Security':[['Require two-factor authentication','Protect administrator accounts.'],['Session timeout','End inactive sessions after 30 minutes.'],['Allow shared accounts','Permit multiple operators per login.']],
  'Integrations':[['Camera network','24 of 24 cameras connected.'],['Access control','Main and north gates synchronized.'],['Property management system','Resident directory synced hourly.']],
}
function Empty({title,text}:{title:string;text:string}){return <div className="grid min-h-52 place-items-center p-8 text-center"><div><span className="table-icon mx-auto"><Bell /></span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{text}</p></div></div>}
function SummaryBox({label,value,icon:Icon}:{label:string;value:string;icon:typeof Bell}){return <article className="panel flex items-center gap-4 p-5"><span className="stat-icon stat-primary"><Icon/></span><div><p className="text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div></article>}
function Detail({label,value}:{label:string;value:string}){return <div className="flex justify-between border-b py-3 text-sm"><span className="text-muted-foreground">{label}</span><strong>{value}</strong></div>}
