'use client'

import { CarFront, ChevronLeft, ChevronRight, Download, Filter, MoreHorizontal, Plus, Search, Upload, UserPlus, Users } from 'lucide-react'
import { useMemo, useState } from 'react'
import { residents, vehicles } from '@/lib/smartpark-data'
import { AdminShell, Modal, PageHeader, Status } from './shell'

export function VehiclesPage() {
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState('All'); const [open, setOpen] = useState(false); const [selected, setSelected] = useState(vehicles[0]);
  const rows = useMemo(() => vehicles.filter(v => (filter === 'All' || v.status === filter) && `${v.plate} ${v.owner} ${v.type}`.toLowerCase().includes(search.toLowerCase())), [search, filter])
  return <AdminShell><PageHeader title="Vehicle management" description="Manage registered vehicles, permits, assignments, and parking status." action={<div className="flex gap-2"><button className="button-secondary"><Upload />Import</button><button className="button-primary" onClick={() => setOpen(true)}><Plus />Add vehicle</button></div>} /><div className="panel overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 md:flex-row"><label className="search-field flex-1"><Search /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search plate, resident, or vehicle" /></label><select value={filter} onChange={e => setFilter(e.target.value)}><option>All</option><option>Parked</option><option>Away</option><option>Pending</option></select><button className="button-secondary"><Filter />More filters</button><button className="button-secondary"><Download />Export</button></div><div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Resident</th><th>Unit</th><th>Space</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(v => <tr key={v.plate}><td><div className="flex items-center gap-3"><span className="table-icon"><CarFront /></span><div><p className="font-mono text-sm font-semibold">{v.plate}</p><p className="text-xs text-muted-foreground">{v.type}</p></div></div></td><td className="font-medium">{v.owner}</td><td>{v.unit}</td><td className="font-mono">{v.spot}</td><td><Status tone={v.status === 'Parked' ? 'success' : v.status === 'Away' ? 'neutral' : 'warning'}>{v.status}</Status></td><td><button className="icon-button" onClick={() => { setSelected(v); setOpen(true) }}><MoreHorizontal /></button></td></tr>)}</tbody></table></div><Pagination count={rows.length} /></div><Modal open={open} onClose={() => setOpen(false)} title={selected ? `Vehicle ${selected.plate}` : 'Add vehicle'}><form className="flex flex-col gap-4" onSubmit={e => { e.preventDefault(); setOpen(false) }}><div className="grid gap-4 sm:grid-cols-2"><label className="field"><span>License plate</span><input defaultValue={selected?.plate} required /></label><label className="field"><span>Space</span><input defaultValue={selected?.spot} /></label></div><label className="field"><span>Resident</span><input defaultValue={selected?.owner} required /></label><label className="field"><span>Vehicle details</span><input defaultValue={selected?.type} required /></label><div className="mt-2 flex justify-end gap-2"><button type="button" className="button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="button-primary">Save vehicle</button></div></form></Modal></AdminShell>
}

export function ResidentsPage() {
  const [search, setSearch] = useState(''); const [open, setOpen] = useState(false); const [selected, setSelected] = useState(residents[0]);
  const rows = residents.filter(r => `${r.name} ${r.email} ${r.unit}`.toLowerCase().includes(search.toLowerCase()))
  return <AdminShell><PageHeader title="Residents" description="Manage community members, unit access, vehicles, and parking privileges." action={<button className="button-primary" onClick={() => setOpen(true)}><UserPlus />Add resident</button>} /><section className="mb-4 grid gap-4 sm:grid-cols-3"><Summary label="Total residents" value="1,438" detail="Across 1,102 units" /><Summary label="Active permits" value="1,284" detail="89.3% participation" /><Summary label="Pending invitations" value="24" detail="8 expire this week" /></section><div className="panel overflow-hidden"><div className="flex flex-col gap-3 border-b p-4 md:flex-row"><label className="search-field flex-1"><Search /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search resident, email, or unit" /></label><button className="button-secondary"><Filter />Filter</button><button className="button-secondary"><Download />Export</button></div><div className="table-wrap"><table><thead><tr><th>Resident</th><th>Unit</th><th>Vehicles</th><th>Status</th><th>Access</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map(r => <tr key={r.email}><td><div className="flex items-center gap-3"><span className="avatar">{r.initials}</span><div><p className="font-semibold">{r.name}</p><p className="text-xs text-muted-foreground">{r.email}</p></div></div></td><td className="font-mono">{r.unit}</td><td>{r.vehicles} registered</td><td><Status tone={r.status === 'Active' ? 'success' : r.status === 'Pending' ? 'warning' : 'danger'}>{r.status}</Status></td><td><span className="text-sm">Garage + Guest</span></td><td><button className="icon-button" onClick={() => { setSelected(r); setOpen(true) }}><MoreHorizontal /></button></td></tr>)}</tbody></table></div><Pagination count={rows.length} /></div><Modal open={open} onClose={() => setOpen(false)} title={selected ? selected.name : 'Add resident'} compact><form className="flex flex-col gap-4" onSubmit={e => { e.preventDefault(); setOpen(false) }}><label className="field"><span>Full name</span><input defaultValue={selected?.name} required /></label><label className="field"><span>Email address</span><input type="email" defaultValue={selected?.email} required /></label><div className="grid gap-4 sm:grid-cols-2"><label className="field col-span-2"><span>Password</span><input type="password" placeholder="••••••••" autoComplete="new-password" /></label><label className="field"><span>Unit</span><input defaultValue={selected?.unit} required /></label><label className="field"><span>Status</span><select defaultValue={selected?.status}><option>Active</option><option>Pending</option><option>Suspended</option></select></label></div><div className="mt-2 flex justify-end gap-2"><button type="button" className="button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="button-primary">Save resident</button></div></form></Modal></AdminShell>
}

function Summary({ label,value,detail}:{label:string;value:string;detail:string}) { return <article className="panel flex items-center gap-4 p-5"><span className="stat-icon stat-primary"><Users /></span><div><p className="text-2xl font-bold">{value}</p><p className="text-sm font-medium">{label}</p><p className="text-xs text-muted-foreground">{detail}</p></div></article> }
function Pagination({count}:{count:number}) { return <div className="flex items-center justify-between border-t px-4 py-3"><p className="text-xs text-muted-foreground">Showing {count} of 1,284 records</p><div className="flex gap-1"><button className="icon-button" disabled><ChevronLeft /></button><button className="pagination-active">1</button><button className="pagination-button">2</button><button className="pagination-button">3</button><button className="icon-button"><ChevronRight /></button></div></div> }
